# Generated by Django 5.2.8 on 2025-11-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('income', models.FloatField()),
                ('city', models.CharField(max_length=100)),
                ('property_type', models.CharField(max_length=100)),
                ('budget', models.FloatField()),
                ('followups', models.IntegerField()),
                ('site_visited', models.BooleanField()),
                ('booked', models.BooleanField()),
            ],
        ),
    ]
